# Machine Learning Applied to Cervical Cancer Data
- Given a dataset with 36 columns
  - 32 feature columns, 4 target columns
- Created a model using KNN to predict presence of cervical cancer for given feature values for a patient.

## Importing data and libraries

In [1]:
from google.colab import files
uploaded = files.upload()

Saving cervical-cancer.csv to cervical-cancer.csv


In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [11]:
df = pd.read_csv("cervical-cancer.csv")

In [12]:
df.describe()

Age  Number of sexual partners  ...    Citology      Biopsy
count  835.000000                 810.000000  ...  835.000000  835.000000
mean    27.023952                   2.551852  ...    0.051497    0.064671
std      8.482986                   1.676686  ...    0.221142    0.246091
min     13.000000                   1.000000  ...    0.000000    0.000000
25%     21.000000                   2.000000  ...    0.000000    0.000000
50%     26.000000                   2.000000  ...    0.000000    0.000000
75%     32.000000                   3.000000  ...    0.000000    0.000000
max     84.000000                  28.000000  ...    1.000000    1.000000

[8 rows x 36 columns]

## Feature Engineering

- Adding values of different test into a new target and dropping the 4 target columns(tests columns)
- Replacing values in target column as: if value > 0 value = 1 else value = 0
- Using the 25 columns mentioned in the paper
- Replacing Nan values by median of the columns

In [13]:
# Making a single target column
target_columns = ['Hinselmann', 'Schiller', 'Citology', 'Biopsy']
target_column = df['Hinselmann'] + df['Schiller'] + df['Citology'] + df['Biopsy'] 
df['target'] = target_column
df.loc[df['target'] != 0, ['target']] = 1

# feature selection
features_selected = ['Age', 'Number of sexual partners', 'First sexual intercourse', 'Num of pregnancies', 'Smokes', 'Smokes (years)', 'Smokes (packs/year)','Hormonal Contraceptives', 'Hormonal Contraceptives (years)', 
'IUD', 'IUD (years)', 'STDs', 'STDs (number)', 'STDs:condylomatosis', 'STDs:cervical condylomatosis', 'STDs:vaginal condylomatosis', 'STDs:vulvo-perineal condylomatosis', 'STDs:syphilis','STDs:pelvic inflammatory disease', 'STDs:genital herpes',
'STDs:molluscum contagiosum', 'STDs:AIDS', 'STDs:HIV','STDs:Hepatitis B', 'STDs:HPV', 'target']

for i in df.columns:
  if i not in features_selected:
    df = df.drop(i, axis="columns")

# Replacing Nan by median
  
df = df.replace('?', np.NaN)
for i in df.columns:
  df[i] = df[i].fillna((df[i].median()))
  

## Model, predictions and accuracy
- Using K_fold with 5 folds
- using KNN with 5 neighbors
- using confusion matrix for model accuracy evaluation

In [14]:
X = df.drop('target', axis = 1) 
y = df.target
scores=[]


kf = KFold(n_splits=5)

for train_index, test_index in kf.split(df):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

  model = KNeighborsClassifier(n_neighbors = 5, metric='euclidean')
  model.fit(X_train, y_train)
  
  y_pred = model.predict(X_test) 

  print("Score:", metrics.accuracy_score(y_test, y_pred))
  cm = confusion_matrix(y_test, y_pred)
  print(cm, "\n")

'''confusion matrix 
  [[TP, FN]
  [FP, TN]]
'''


Score: 0.8622754491017964
[[144   4]
 [ 19   0]] 

Score: 0.8862275449101796
[[148   2]
 [ 17   0]] 

Score: 0.8562874251497006
[[143   1]
 [ 23   0]] 

Score: 0.8502994011976048
[[142   0]
 [ 25   0]] 

Score: 0.8922155688622755
[[149   1]
 [ 17   0]] 



'confusion matrix \n  [[TP, FN]\n  [FP, TN]]\n'

## RDBMS IA 2 -> Implementation of paper

- 1911089 Vedant